apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapphub
spec:
  selector:
    matchLabels:
      app: myapphub
  replicas: 2
  template:
    metadata:
      labels:
        app: myapphub
    spec:
      containers:
      - name: myapphub
        image: nanajanashia/argocd-app:1.0
        ports:
        - containerPort: 8080
